using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BombAction : MonoBehaviour
{
    public GameObject bombEffect;

    public int attackPower = 10;
    public float explosionRadius = 5f;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    private void OnCollisionEnter(Collision collision)
    {
        // 폭발 효과 반경 내에서 레이어가 'Enemy'인 모든 게임 오브젝트들의 Collider 컴포넌트를 배열에 저장한다.
        Collider[] cols = Physics.OverlapSphere(transform.position, explosionRadius, 1 << 8); // 레이어의 순서를 바꾸는게 1<<8이라는데 잘 모르겠음.
        for(int i = 0; i < cols.Length; i++)
        {
            cols[i].GetComponent<EnemyFSM>().HitEnemy(attackPower);
        }
        GameObject eff = Instantiate(bombEffect);

        eff.transform.position = transform.position;
        
        Destroy(gameObject);
    }
}
